name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build And Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Make Fake API Server Version File
        run: echo -123456 > "API Server Version.txt"
      - name: Test with Pytest
        run: pytest --cov . --cov-report=xml --cov-report=html --cov-config=.coveragerc
        shell: bash
      - name: Upload Coverage Report to CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
#      - name: Upload PyTest Coverage HTML File
#        uses: actions/upload-artifact@v3
#        with:
#          name: PyTest_Coverage_Report
#          path: htmlcov
